apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-creator
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    #  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configmap-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-creator
subjects:
  - kind: ServiceAccount
    name: configmap-creator
    namespace: default
roleRef:
  kind: Role
  name: configmap-creator
  apiGroup: rbac.authorization.k8s.io
