apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook-<DATASET_ID_LOWER>
  labels:
    app: jupyter-notebook-<DATASET_ID_LOWER>
    nb-type: <DATASET_ID_LOWER>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook-<DATASET_ID_LOWER>
  template:
    metadata:
      labels:
        app: jupyter-notebook-<DATASET_ID_LOWER>
        nb-type: <DATASET_ID_LOWER>
    spec:
      securityContext:
        fsGroup: 65533 # to make SSH key readable
      imagePullSecrets:
        - name: docker-creds
      initContainers:
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.1
          imagePullPolicy: Always
          env:
            - name: GIT_SYNC_REPO
              value: "<GIT_REPO>"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SYNC_ROOT
              value: "/repo"
            - name: GIT_SYNC_DEST
              value: "<REPO_NAME>"
            - name: GIT_SYNC_BRANCH
              value: "<BRANCH>"
          volumeMounts:
            - name: git-secret
              mountPath: /etc/git-secret
            - name: git-repo
              mountPath: /repo
          securityContext:
            runAsUser: 65533 # git-sync user
        - name: gcloud-dataset-sync
          image: google/cloud-sdk:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/certs"
              name: gcloud-certs
              readOnly: true
            - mountPath: "/transfer"
              name: gcloud-data
          command:
            - sh
            - -c
            - |
              gcloud auth activate-service-account --key-file=/certs/svc_account.json

              echo "<BUCKET_SUBPATHS>" | tr ',' '\n' | while read subpath; do
                gsutil cp -r "<GCLOUD_EXP_BASE>/${subpath}" /transfer/
              done
      containers:
        - name: notebook
          image: jupyter/scipy-notebook:latest
#          image: stepankuzmin/pytorch-notebook
          ports:
          - containerPort: 8888
          command: ["start-notebook.sh"]
          args: ["--NotebookApp.token=''"]
          volumeMounts:
            - mountPath: "/home/jovyan/<REPO_NAME>"
              subPath: "<REPO_NAME>"
              name: git-repo
            - mountPath: "/home/jovyan/gcloud_data"
              name: gcloud-data
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: gcloud-data
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-creds
            defaultMode: 288
        - name: gcloud-certs
          secret:
            secretName: gcloud-creds
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook-<DATASET_ID_LOWER>
spec:
  type: ClusterIP
  selector:
    app: jupyter-notebook-<DATASET_ID_LOWER>
  ports:
  - protocol: TCP
    #nodePort: 30040
    port: 8988
    targetPort: 8888
