apiVersion: v1
kind: ServiceAccount
metadata:
  name: canela-jenkins
  namespace: default
  labels:
      name: canela-jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: canela-jenkins-schedule-agents
subjects:
- kind: ServiceAccount
  name: canela-jenkins
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
