apiVersion: v1
kind: Secret
metadata:
  name: gcloud-creds
type: Opaque
data:
  svc_account.json: <GCLOUD_CREDS>
---
apiVersion: v1
kind: Secret
metadata:
  name: gcloud-creds
  namespace: kubeflow
type: Opaque
data:
  svc_account.json: <GCLOUD_CREDS>
---
apiVersion: v1
kind: Secret
metadata:
  name: kaggle-creds
type: Opaque
data:
  kaggle.json: <KAGGLE_CREDS>
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <DOCKER_CREDS>
---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds
type: Opaque
data:
  ssh: <GIT_PRIVATE_SSH_KEY>
  known_hosts: <KNOWN_HOSTS>

